version: '3.1'
services:

  laravel-app:
    build:
      context: './app'
      args:
        uid: ${UID}
    container_name: laravel-app
    environment:
      - APACHE_RUN_USER=#${UID}
      - APACHE_RUN_GROUP=#${UID}
    volumes:
      - .:/var/www/html
    ports:
      - 8080:80
    networks:
      backend:
        aliases:
          - laravel-app
  php:
    build:
      context: ./app
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - 8000:8000

  mysql-db:
    image: mysql:5.7
    container_name: mysql-db
    ports:
      - "3308:3308"
    volumes:
      - ./run/var:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    networks:
      backend:
        aliases:
          - db

networks:
  backend:
    name: backend-network

