version: '3.1'
services:

  php:
    build:
      context: ./php
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - 8000:8000

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: root
      MYSQL_PASSWORD:
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
#    volumes:
#      - my-db:/var/lib/mysql 
