version: '3.1'
services:

  php:
    build:
      context: ./php
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - 8000:8000

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: root
      MYSQL_PASSWORD: 
